spring:
  application:
    name: auth-service
#  datasource:
#    url: jdbc:mysql://localhost:3336/_db
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true

server:
  port: 8088

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true