spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth-service/**
#          filters:
#            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/auth/**
            - Path=/users/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: import-order-service
          uri: lb://import-order-service
          predicates:
            - Path=/import-orders/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: statistic-service
          uri: lb://statistic-service
          predicates:
            - Path=/statistics/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

jwt:
  secret: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@"
  expiration: 86400

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    register-with-eureka  : true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    com:
      api_gateway=DEBUG:

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    eureka:
      enabled: true