spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:${eureka.instance.hostname}}:${SERVER_PORT:${server.port}}/eureka/
